# Basic
title: Domi●Cat
subtitle: 好记性不如烂笔头
description: "痛苦不止 希望不灭"
# 头像里面的标题
avatarTitle: DomiCat
# 头像里面的描述
avatarDesc: 外出务工人员
url: "http://domicat.me"

# Comment
comment:
    # gitment: domi
    # disqus: domi
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 5366874726
    github: shuimu98
    # twitter:
    mail: shui_mu98@163.com

# 百度统计
# 使用博客模板请去掉或者更换 id
#baidu:
#    id: 8ba1c6be0953b6f9c2ba38e57f615421

# Google Analytics
# 使用博客模板请去掉或者更换 id
#ga:
#    id: UA-71084139-1
#    host: auto
#

# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: Posts

# Navigation buttons in the front page.s
nav:
    - {title: Archives, description: archive, url: '/archive'}
    - {title: Tags, description: tags, url: '/tags'}
    - {title: About, description: about, url: '/about'}


# Pagination
plugins: [jekyll-paginate, jekyll-sitemap]
paginate: 5
paginate_path: "page/:num/"


